# Generated by Django 4.1.1 on 2022-09-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'Доска',
                'verbose_name_plural': 'Доски',
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='BoardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='тип объекта')),
                ('data', models.JSONField(verbose_name='объект доски')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'Объект на доске',
                'verbose_name_plural': 'Объекты на доске',
                'db_table': 'board_data',
            },
        ),
        migrations.CreateModel(
            name='BoardDataBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, verbose_name='тип объекта')),
                ('data', models.JSONField(verbose_name='объект доски')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='доска')),
            ],
            options={
                'verbose_name': 'Удаленный объект',
                'verbose_name_plural': 'Удаленные объекты',
                'db_table': 'board_data_basket',
            },
        ),
    ]
