# Generated by Django 4.1.1 on 2022-09-07 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='group', to=settings.AUTH_USER_MODEL, verbose_name='группа пользователей'),
        ),
    ]
