# Generated by Django 4.1.1 on 2022-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddata',
            name='type',
            field=models.CharField(choices=[('v', 'векторная графика'), ('r', 'растровая графика')], max_length=1, verbose_name='тип объекта'),
        ),
        migrations.AlterField(
            model_name='boarddatabasket',
            name='type',
            field=models.CharField(choices=[('v', 'векторная графика'), ('r', 'растровая графика')], max_length=1, verbose_name='тип объекта'),
        ),
    ]
