# Generated by Django 4.1.1 on 2022-09-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_boarddata_type_alter_boarddatabasket_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boarddata',
            old_name='type',
            new_name='type_object',
        ),
    ]
