# Generated by Django 4.1.1 on 2022-09-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_type_boarddata_type_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoRegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.board', verbose_name='доска')),
            ],
        ),
    ]
