# Generated by Django 4.1.1 on 2022-09-20 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_noregisteruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noregisteruser',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='доска'),
        ),
    ]
