# Generated by Django 4.1.1 on 2022-10-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_noregisteruser_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['id'], 'verbose_name': 'Доска', 'verbose_name_plural': 'Доски'},
        ),
    ]
