# Generated by Django 4.1.1 on 2022-10-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_board_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boarddatabasket',
            old_name='type',
            new_name='type_object',
        ),
    ]
