# Generated by Django 4.1.1 on 2022-10-13 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_rename_type_boarddatabasket_type_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddata',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AddField(
            model_name='boarddatabasket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='создано'),
            preserve_default=False,
        ),
    ]
