# Generated by Django 4.1.1 on 2022-10-16 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_boarddata_created_boarddatabasket_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddatabasket',
            name='type_object_action',
            field=models.CharField(choices=[('u', 'undo'), ('r', 'redo')], default='u', max_length=1, verbose_name='тип действия над объектом'),
            preserve_default=False,
        ),
    ]
