# Generated by Django 4.1.1 on 2022-10-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_boarddatabasket_type_object_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddatabasket',
            name='temp_id',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='id объекта в доске'),
        ),
    ]
