# Generated by Django 4.1.1 on 2022-10-22 12:47

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_boarddatabasket_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noregisteruser',
            name='email',
            field=users.models.LowercaseEmailField(max_length=254, verbose_name='email'),
        ),
    ]
