# Generated by Django 4.1.1 on 2023-01-21 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0014_alter_board_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='доска')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение чата доски',
                'verbose_name_plural': 'Сообщения чата доски',
                'db_table': 'board_message',
            },
        ),
    ]
