# Generated by Django 4.1.1 on 2022-09-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='верифицирован'),
        ),
    ]
