# Generated by Django 4.1.1 on 2022-12-22 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_temporarybanip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='number error', regex='^\\+7\\d{10,10}$')], verbose_name='телефон'),
        ),
    ]
