# Generated by Django 4.1.1 on 2023-01-11 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that phone already exists.'}, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='number error', regex='^\\+7\\d{10,10}$')], verbose_name='телефон'),
        ),
    ]
