# Generated by Django 4.1.1 on 2023-02-04 15:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to, verbose_name='аватарка'),
        ),
    ]
