# Generated by Django 4.1.1 on 2023-02-14 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_friends_friendsrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создана заявка')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('is_active', models.BooleanField(default=True, verbose_name='заявка')),
                ('is_except', models.BooleanField(default=True, verbose_name='принята заявка')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='от кого')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='кому')),
            ],
            options={
                'verbose_name': 'запрос в друзья',
                'verbose_name_plural': 'запрос в друзья',
                'db_table': 'friend_request',
            },
        ),
        migrations.DeleteModel(
            name='FriendsRequest',
        ),
    ]
